#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use App\Framework\Console\Application;

$application = new Application();

// ... register commands

$application->run();